name: Build and Publish to npm

on:
  push:
    branches:
      - master # Adjust for your default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust to your package requirements
          cache: 'npm'

      # Step 3: Configure npm authentication
      - name: Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the package
      - name: Build the package
        run: npm run build

      # Step 6: Publish to npm
      - name: Publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
